import construcao from '../../../public/img/construcao.png'
import placeholder from '../../../public/img/placeholder2.jpg'

export const Data2 = {
  news: [
    {
      id: '1',
      url: construcao,
      title: 'Título 1 - igreja 2',
      description: 'Descrição 1',
      page: 'igreja2',
    },
    {
      id: '2',
      url: construcao,
      title: 'Título 2 - igreja 2',
      description: 'Descrição 2',
      page: 'igreja2',
    },
    {
      id: '3',
      url: construcao,
      title: 'Título 3 - igreja 2',
      description: 'Descrição 3 ',
      page: 'igreja2',
    },
    {
      id: '4',
      url: construcao,
      title: 'Título 4 - igreja 2',
      description: 'Descrição 4',
      page: 'igreja2',
    },
    {
      id: '5',
      url: construcao,
      title: 'Título 5 - igreja 2',
      description: 'Descrição 5',
      page: 'igreja2',
    },
    {
      id: '6',
      url: construcao,
      title: 'Título 6 - igreja 2',
      description: 'Descrição 6',
      page: 'igreja2',
    },
    {
      id: '7',
      url: construcao,
      title: 'Título 7 - igreja 2',
      description: 'Descrição 7',
      page: 'igreja2',
    },
  ],
  agenda: [
    {
      day: 'Domingo - igreja 2',
      title: 'Escola bíblica dominical',
      hora: '08:00/10:00',
      titletwo: 'Culto de adoração',
      horatwo: '10:00/12:00',
      trueitem: true,
    },
    {
      day: 'Segunda - igreja 2',
      title: 'Culto de consagração',
      hora: '19:30/21:30',
      titletwo: false,
      horatwo: false,
      trueitem: false,
    },
    {
      day: 'Terça - igreja 2',
      title: 'Projeto Jiu-Jitsu',
      hora: '19:00/21:00',
      titletwo: false,
      horatwo: false,
      trueitem: false,
    },
    {
      day: 'Quarta - igreja 2',
      title: 'Culto em busca do  Espírito Santo',
      hora: '18:30/20:30',
      titletwo: false,
      horatwo: false,
      trueitem: false,
    },
    {
      day: 'Sexta - igreja 2',
      title: 'Projeto Jiu-Jitsu',
      hora: '19:00/21:00',
      titletwo: false,
      horatwo: false,
      trueitem: false,
    },
    {
      day: 'Sábado - igreja 2',
      title: 'Dia das delícias',
      hora: '18:30/22:00',
      titletwo: false,
      horatwo: false,
      trueitem: false,
    },
  ],
  ministerio: [
    {
      id: '1',
      nome: 'Nome 1',
      titulo: 'Pastor Dirigente',
      local: 'Igreja 2',
      img: placeholder,
    },
    {
      id: '2',
      nome: 'Nome 2',
      titulo: 'Pastora',
      local: 'Igreja 2',
      img: placeholder,
    },
    {
      id: '3',
      nome: 'Nome 3',
      titulo: 'Presbítero',
      local: 'Igreja 2',
      img: placeholder,
    },
    {
      id: '4',
      nome: 'Nome 4',
      titulo: 'Diácono',
      local: 'Igreja 2',
      img: placeholder,
    },
  ],
}
