export const dataAgenda = [
  {
    day: 'Domingo',
    title: 'Escola bíblica dominical',
    hora: '08:00/10:00',
    titletwo: 'Culto de adoração',
    horatwo: '10:00/12:00',
    trueitem: true,
  },
  {
    day: 'Segunda',
    title: 'Culto de consagração',
    hora: '19:30/21:30',
    titletwo: false,
    horatwo: false,
    trueitem: false,
  },
  {
    day: 'Terça',
    title: 'Projeto Jiu-Jitsu',
    hora: '19:00/21:00',
    titletwo: false,
    horatwo: false,
    trueitem: false,
  },
  {
    day: 'Quarta',
    title: 'Culto em busca do  Espírito Santo',
    hora: '18:30/20:30',
    titletwo: false,
    horatwo: false,
    trueitem: false,
  },
  {
    day: 'Sexta',
    title: 'Projeto Jiu-Jitsu',
    hora: '19:00/21:00',
    titletwo: false,
    horatwo: false,
    trueitem: false,
  },
  {
    day: 'Sábado',
    title: 'Dia das delícias',
    hora: '18:30/22:00',
    titletwo: false,
    horatwo: false,
    trueitem: false,
  },
]
